Q1. Create a NumPy array of integers from 1 to 10

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q2. Create a 2x3 NumPy array filled with zeros


In [ ]:
arr2=np.zeros((2,3))

In [ ]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

Q3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr3=np.arange(2,21,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

 Q4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr4=arr1-arr2
arr4

array([-3, -3, -3])

In [ ]:
arr5=arr1*arr2
arr5

array([ 4, 10, 18])

In [ ]:
arr6=arr1/arr2
arr6

array([0.25, 0.4 , 0.5 ])

Q5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [ ]:
arr1=np.random.rand(100)

In [ ]:
arr1

array([0.60197261, 0.79880924, 0.61533876, 0.77430718, 0.73079552,
       0.36563658, 0.44795209, 0.67121786, 0.70505151, 0.56902651,
       0.55321741, 0.14977355, 0.63424281, 0.13250966, 0.95284332,
       0.87051304, 0.85388673, 0.69504304, 0.93160364, 0.44617148,
       0.65428696, 0.3322454 , 0.25616156, 0.89667135, 0.70561906,
       0.38114836, 0.37113347, 0.46094099, 0.80528571, 0.01842903,
       0.93121798, 0.70178109, 0.71371205, 0.17704656, 0.27155348,
       0.21346674, 0.1437542 , 0.84624696, 0.50811895, 0.48759391,
       0.04263484, 0.82959358, 0.0188318 , 0.00118005, 0.85753281,
       0.19529599, 0.83094555, 0.18350736, 0.51696301, 0.45709972,
       0.95590029, 0.79918931, 0.30508935, 0.53050962, 0.61031093,
       0.18985786, 0.56647699, 0.74713738, 0.38678938, 0.13249444,
       0.76470804, 0.93567743, 0.42930102, 0.87439806, 0.9803012 ,
       0.31284762, 0.15648214, 0.78825402, 0.12428994, 0.34479283,
       0.73069529, 0.85602881, 0.39976697, 0.74434831, 0.01319

In [ ]:
arr1.mean()

0.48254515420337685

In [ ]:
np.median(arr1)

0.464370666112644

In [ ]:
arr1.std()

0.30858678606912765

Q6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr6=np.random.rand(12)

In [ ]:
arr6

array([0.37396335, 0.40489828, 0.61264279, 0.1171641 , 0.89928402,
       0.19000119, 0.02419502, 0.58377213, 0.70714524, 0.01643797,
       0.23990963, 0.7813828 ])

In [ ]:
arr6.reshape(3,4)

array([[0.37396335, 0.40489828, 0.61264279, 0.1171641 ],
       [0.89928402, 0.19000119, 0.02419502, 0.58377213],
       [0.70714524, 0.01643797, 0.23990963, 0.7813828 ]])

Q7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [ ]:
arr7=([1,2,3,4,5])

In [ ]:
np.square(arr7)

array([ 1,  4,  9, 16, 25])

Q8. Create a 5x5 identity matrix using NumPy

In [ ]:
arr8=np.eye(5,5)
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Q9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

Q10.Find the index of the maximum value and the index of the minimum value
in a NumPy array

In [ ]:
arr10=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr10.argmax()

9

In [ ]:
arr10.argmin()

0

Q11.Concatenate two random NumPy arrays horizontally and vertically.

In [ ]:
A=np.random.rand(4,4)
A

array([[0.90687753, 0.79864139, 0.86746713, 0.58998104],
       [0.2959709 , 0.50645754, 0.96743686, 0.40297891],
       [0.3683331 , 0.88392148, 0.79143003, 0.78336813],
       [0.07416534, 0.58450265, 0.23612946, 0.01110146]])

In [ ]:
B=np.random.rand(4,4)
B

array([[0.87143504, 0.05531904, 0.26282504, 0.88325503],
       [0.17699266, 0.49078239, 0.39624197, 0.25449946],
       [0.73815492, 0.90135918, 0.86286   , 0.67255822],
       [0.05999845, 0.54415931, 0.66872555, 0.73782055]])

In [ ]:
np.concatenate((A,B))  #vertically

array([[0.90687753, 0.79864139, 0.86746713, 0.58998104],
       [0.2959709 , 0.50645754, 0.96743686, 0.40297891],
       [0.3683331 , 0.88392148, 0.79143003, 0.78336813],
       [0.07416534, 0.58450265, 0.23612946, 0.01110146],
       [0.87143504, 0.05531904, 0.26282504, 0.88325503],
       [0.17699266, 0.49078239, 0.39624197, 0.25449946],
       [0.73815492, 0.90135918, 0.86286   , 0.67255822],
       [0.05999845, 0.54415931, 0.66872555, 0.73782055]])

In [ ]:
np.concatenate((A,B),axis=1)  #horizontally

array([[0.90687753, 0.79864139, 0.86746713, 0.58998104, 0.87143504,
        0.05531904, 0.26282504, 0.88325503],
       [0.2959709 , 0.50645754, 0.96743686, 0.40297891, 0.17699266,
        0.49078239, 0.39624197, 0.25449946],
       [0.3683331 , 0.88392148, 0.79143003, 0.78336813, 0.73815492,
        0.90135918, 0.86286   , 0.67255822],
       [0.07416534, 0.58450265, 0.23612946, 0.01110146, 0.05999845,
        0.54415931, 0.66872555, 0.73782055]])

Q12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [43]:
arr1=np.array([[4,5,6],[7,8,9],[1,2,3]])
arr1

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [45]:
arra=arr1[0:1,[0,1,2]]  #first row

In [52]:
arra.sum()

15

In [47]:
arrb=arr1[1:2,[0,1,2]]  #second row

In [53]:
arrb.sum()

24

In [49]:
arrc=arr1[2:3,[0,1,2]]  #third row

In [51]:
arrc.sum()

6

In [55]:
arra=arr1[:,[0]]   #first column

In [56]:
arra.sum()

12

In [57]:
arrb=arr1[:,[1]]   #second column

In [58]:
arrb.sum()

15

In [59]:
arrc=arr1[:,[2]]   #third column

In [60]:
arrc.sum()

18

Q13.Find the common elements between two NumPy arrays.

In [ ]:
arr1=np.array([5,8,11,10,6,4])
arr2=np.array([1,2,3,4,5,6])

In [ ]:
arr1

array([ 5,  8, 11, 10,  6,  4])

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.intersect1d(arr1,arr2)

array([4, 5, 6])

Q14.Replace all negative values in a NumPy array with zeros.

In [ ]:
arr14=np.array([-5,-4,-3,-2,-1,1,2,3,4,5])
arr14

array([-5, -4, -3, -2, -1,  1,  2,  3,  4,  5])

In [ ]:
arr14[arr14<0]=0
arr14

array([0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

Q15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order

In [ ]:
arr15=np.random.randint(1,101,100)
arr15

array([ 69,  42,   1,  93,  46,  92,  85,  60,  57,  79,  46,  97,  53,
        45,  17,  46,  99,  90,  85,  41,  52,  53,  38,  33,  57,  61,
        35,  43,  23,  47,  67,  77,  59,  86,  54,  32,  96,   4,  67,
         5,  85,  52,   3,  80,  73,  25,  27,  43,  49,  58,  52, 100,
        85,  67, 100,  36,  32,  31,  70,  17,  43,  31,   5,  58,  12,
        35,  21,  13,  30,  27,   6,   2,  43,   3,  53,  91,  16,  30,
        40,  49,  18,  10,   6,  28,  78,  93,  77,   1,  22,  15,   7,
        29,  51,  19,  34,  23,  78,  21,  13,  54])

In [ ]:
arr15.sort()
arr15

array([  1,   1,   2,   3,   3,   4,   5,   5,   6,   6,   7,  10,  12,
        13,  13,  15,  16,  17,  17,  18,  19,  21,  21,  22,  23,  23,
        25,  27,  27,  28,  29,  30,  30,  31,  31,  32,  32,  33,  34,
        35,  35,  36,  38,  40,  41,  42,  43,  43,  43,  43,  45,  46,
        46,  46,  47,  49,  49,  51,  52,  52,  52,  53,  53,  53,  54,
        54,  57,  57,  58,  58,  59,  60,  61,  67,  67,  67,  69,  70,
        73,  77,  77,  78,  78,  79,  80,  85,  85,  85,  85,  86,  90,
        91,  92,  93,  93,  96,  97,  99, 100, 100])

Q16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [79]:
arr1=np.array([6,7,8,9,-10])
arr2=np.array([1,2,3,4,5])

In [80]:
arr1

array([  6,   7,   8,   9, -10])

In [81]:
arr2

array([1, 2, 3, 4, 5])

In [82]:
arr3=np.abs(arr1-arr2)
arr3

array([ 5,  5,  5,  5, 15])

Q17.Given a 2D NumPy array, extract the first row and the last column

In [ ]:
arr1=np.array([[2,5,6,7,8,5,4,9],[5,6,7,11,13,8,12,10]])
arr1

array([[ 2,  5,  6,  7,  8,  5,  4,  9],
       [ 5,  6,  7, 11, 13,  8, 12, 10]])

In [ ]:
arr1[:,[7]]    #last column

array([[ 9],
       [10]])

In [ ]:
arr1[0:1,[0,1,2,3,4,5,6,7]]    #first row

array([[2, 5, 6, 7, 8, 5, 4, 9]])

Q18.Slice a 1D NumPy array to get every other element

In [62]:
arr1=np.array([1,2,3,4,5,6,7,8])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
arr1[0:9:2]

array([1, 3, 5, 7])

Q19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [ ]:
arr19=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr19

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr19[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

Q20.Reverse a 1D NumPy array using slicing.

In [ ]:
arr20=np.array([1,3,5,7,9])
arr20

array([1, 3, 5, 7, 9])

In [ ]:
arr20[::-1]

array([9, 7, 5, 3, 1])